# Generated by Django 2.2.1 on 2020-04-24 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sump', models.IntegerField(default=0, verbose_name='收藏人数')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='歌曲名称')),
                ('artist', models.CharField(max_length=128, verbose_name='歌手')),
                ('album', models.CharField(max_length=128, verbose_name='专辑名称')),
                ('years', models.CharField(max_length=128, verbose_name='年份')),
                ('lyric', models.TextField(verbose_name='歌词')),
                ('num', models.IntegerField(default=0, verbose_name='浏览量')),
                ('pic', models.URLField(max_length=256, verbose_name='封面图片')),
            ],
            options={
                'verbose_name': '歌曲',
                'verbose_name_plural': '歌曲',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='标签')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128, unique=True, verbose_name='账号')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('phone', models.CharField(max_length=128, verbose_name='手机号码')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='名字')),
                ('address', models.CharField(max_length=128, verbose_name='地址')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.FloatField(verbose_name='评分')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('music', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Music', verbose_name='歌曲id')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='用户id')),
            ],
            options={
                'verbose_name': '评分信息',
                'verbose_name_plural': '评分信息',
            },
        ),
        migrations.AddField(
            model_name='music',
            name='collect',
            field=models.ManyToManyField(blank=True, to='user.User', verbose_name='收藏者'),
        ),
        migrations.AddField(
            model_name='music',
            name='tags',
            field=models.ManyToManyField(blank=True, to='user.Tags', verbose_name='标签'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=64, verbose_name='内容')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('good', models.IntegerField(default=0, verbose_name='点赞')),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Music', verbose_name='歌曲')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
    ]
